export default {
  na: 'não',
  e: 'é',
  mt: 'muito',
  vc: 'você',
  pq: 'porque',
  tb: 'também',
  qd: 'quando',
  d: 'de',
  q: 'que',
  cmg: 'comigo',
  td: 'tudo',
  pra: 'para',
  voce: 'você',
  ta: 'está',
  ai: 'aí',
  to: 'estou',
  tá: 'está',
  tô: 'estou',
  bolsonaro: 'Bolsonaro',
  lula: 'Lula',
  dilma: 'Dilma',
  temer: 'Temer',
  marina: 'Marina',
  alckmin: 'Alckmin',
  haddad: 'Haddad',
  ciro: 'Ciro',
  pt: 'PT',
  psdb: 'PSDB',
  psl: 'PSL',
  facebook: 'Facebook',
  google: 'Google',
  microsoft: 'Microsoft',
  apple: 'Apple',
  nike: 'Nike',
  nestle: 'Nestlé',
  carrefour: 'Carrefour',
  ambev: 'Ambev',
  embraer: 'Embraer',
  itaú: 'Itaú',
  bradesco: 'Bradesco',
  bancodobrasil: 'Banco do Brasil',
  votorantim: 'Votorantim',
  marfrig: 'Marfrig',
  jbs: 'JBS',
  manaus: 'Manaus',
  recife: 'Recife',
  fortaleza: 'Fortaleza',
  salvador: 'Salvador',
  brasília: 'Brasília',
  belém: 'Belém',
  portoalegre: 'Porto Alegre',
  sãopaulo: 'São Paulo',
  riodejaneiro: 'Rio de Janeiro',
  curitiba: 'Curitiba',
  'pao de queijo': 'pão de queijo',
  neymar: 'Neymar',
  ronaldo: 'Ronaldo',
  gisele: 'Gisele',
  havaianas: 'Havaianas',
  oi: 'Oi',
  braskem: 'Braskem',
  itaipu: 'Itaipu',
  amazônia: 'Amazônia',
  caatinga: 'Caatinga',
  pantanal: 'Pantanal',
  ipanema: 'Ipanema',
  sãojoão: 'São João',
  olinda: 'Olinda',
  gramado: 'Gramado',
  santos: 'Santos',
  oab: 'OAB',
  brf: 'BRF',
  petrobras: 'Petrobras',
  eletrobras: 'Eletrobras',
  itaúsa: 'Itaúsa',
  bndes: 'BNDES',
  rodrigomaia: 'Rodrigo Maia',
  gilmar: 'Gilmar',
  'mercedes-benz': 'Mercedes-Benz',
  volkswagen: 'Volkswagen',
  bmw: 'BMW',
  renault: 'Renault',
  tim: 'TIM',
  caixa: 'Caixa',
  hypera: 'Hypera',
  'magazine-luiza': 'Magazine Luiza',
  centauro: 'Centauro',
  nectar: 'Nectar',
  vcê: 'você',
  tbm: 'também',
  'pq?': 'por quê?',
  n: 'não',
  s: 'sim',
  cm: 'com',
  smp: 'sempre',
  tmb: 'também',
  blz: 'beleza',
  vlw: 'valeu',
  obg: 'obrigado',
  obgd: 'obrigado',
  rsrs: 'risos',
  kkk: 'risos',
  hj: 'hoje',
  agr: 'agora',
  eh: 'é',
  so: 'só',
  tamo: 'estamos',
  flw: 'falou',
  msg: 'mensagem',
  pfv: 'por favor',
  vdd: 'verdade',
  tmj: 'estamos juntos',
  pdc: 'pode crer',
  tdb: 'tudo bem',
  fds: 'fim de semana',
  bj: 'beijo',
  bjs: 'beijos',
  abs: 'abraços',
  parabéns: 'Parabéns',
  felizaniversario: 'Feliz Aniversário',
  felizniver: 'Feliz Aniversário',
  feliznatal: 'Feliz Natal',
  felizanonovo: 'Feliz Ano Novo',
  páscoa: 'Páscoa',
  brasil: 'Brasil'
} as { [key: string]: string };
